### PR TITLE
update TFC+ map: yew leaves & all branches

### PR DESCRIPTION
**Pull request by facetorched**
I also tried adding alias for the sling (as a bow) the sound effects lined up perfectly... it just didn't sound right.

### CODE REVIEW

**Comment by makamys** [comment]
Thanks!

About the sling, I'd be open to adding fitting sounds for it to Zen, I just need some good sounds.

(I will also at some point have to figure out a way to extend the concept of aliasing so it can be used with items that have no vanilla equivalent, I'll have to give that some thought.)

**Comment by facetorched** [comment]
Awesome thanks @makamys 

I was also considering also adding an alias for TFC+ shears but it would seem like the default soundpacks don't provide sounds for shears.

Similar thing with the TFC+ fishing rod, I tried adding the alias and it made it sound like the wood sword which i didn't really feel like it fit.

lastly, wouldn't it make more sense to put any new item sounds into mat_default2016? since all of the item switches/use sounds are already in there. Or could make a new soundpack.

**Comment by makamys** [comment]
> lastly, wouldn't it make more sense to put any new item sounds into mat_default2016?

Hm, maybe. I wasn't planning to add new features to that pack, only maintain it, as I consider it something like a time capsule. But it's true that it would be less confusing to have all the item sounds in one place. I think what I'll do is add Default's item sounds to Zen, and work from there. Then I can modify them without any reservations.

> Or could make a new soundpack.

I'll say no to that one, telling users to install two packs to get the "official" experience is already a lot, I don't want to increase that number to three!

**Comment by facetorched** [comment]
@makamys that makes sense although I typically only play with the 2016 pack since zen is nearly 50 MB which I think is quite big for a resourcepack! I do enjoy some of its sounds, specifically the rain on water is very nice.

I'm wondering though, how does MAtmos handle duplicate entries for the same event? For example, if Zen adds an itemswitch sound for the same item as default2016.

Thanks!

**Comment by makamys** [comment]
> since zen is nearly 50 MB which I think is quite big for a resourcepack!

Oh, that's a good point. I could package alternate versions with only the item sounds, that way people could choose if they want to download the entire thing, or just that part.

> I'm wondering though, how does MAtmos handle duplicate entries for the same event?

I'm pretty sure what would happen right now is both sounds would play at the same time. I've thought about this, and intend to solve it by letting expansions declare a list of *categories* that they belong to.

If two expansions with the "item switch" category are active, that would be a conflict MAtmos could detect. It would mute conflicting expansions when they are first added, only keeping the one in the top resource pack unmuted. The GUI would make it clear what's going on and allow you to choose a different resolution (including activating both expansions at the same time in case that's what you really want.)

**Pull request merged**
